import { writeFileSync } from 'node:fs';
import { runConformance } from '../src/conformance/run.js';
import { GOLDEN_MODULE_PATH, GOLDEN_PATH } from './paths.js';

/**
 * Regenerates the golden file from Node.
 *
 * Run this only when a change to the engine is *meant* to change what it
 * decides — and read the diff. Every line that moves is a behaviour that moved
 * on every phone, browser and server at once.
 *
 * It also writes the same bytes as a module, which an app imports to run the
 * corpus on a device (P13).
 */
const golden = `${runConformance()}\n`;
writeFileSync(GOLDEN_PATH, golden, 'utf8');
writeFileSync(
  GOLDEN_MODULE_PATH,
  [
    '// Generated by `pnpm --filter @integr8/form-engine conformance:golden` from',
    '// conformance/golden.jsonl. Do not edit: the conformance test fails if the two differ.',
    `export const GOLDEN = ${JSON.stringify(golden)};`,
    '',
  ].join('\n'),
  'utf8',
);
console.log(`Wrote ${GOLDEN_PATH} and ${GOLDEN_MODULE_PATH}`);
